export const categories = [
    'Animals and Pets',
    'Anime',
    'Art',
    'Careers',
    'Cars and Motor Vehicles',
    'Crypto',
    'Economics and Finance',
    'Family and Relationships',
    'Fitness and Nutrition',
    'Food and Drink',
    'Funny and Humor',
    'Gaming',
    'History',
    'Hobbies',
    'Home and Garden',
    'Law',
    'Education',
    'Marketplace',
    'Military',
    'Movies',
    'Music',
    'Nature',
    'Politics',
    'Programming',
    'Literature',
    'Religion',
    'Science',
    'Sports',
    'Technology',
    'Television',
    'Travel',
    'World News',
    'Other'
]

export const categoriesLookup = [
    'animals_and_pets',
    'anime',
    'art',
    'careers',
    'cars_and_motor_vehicles',
    'crypto',
    'economics_and_finance',
    'family_and_relationships',
    'fitness_and_nutrition',
    'food_and_drink',
    'funny_and_humor',
    'gaming',
    'history',
    'hobbies',
    'home_and_garden',
    'law',
    'education',
    'marketplace',
    'military',
    'movies',
    'music',
    'nature',
    'politics',
    'programming',
    'literature',
    'religion',
    'science',
    'sports',
    'technology',
    'television',
    'travel',
    'world_news',
    'other'
]